import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generatePlantingGuidePDF = (guide: any) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // Header
    // Green background
    doc.setFillColor(22, 163, 74); // green-600
    doc.rect(0, 0, pageWidth, 25, 'F');

    // Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(`Planting Guide: ${guide.crop_type.charAt(0).toUpperCase() + guide.crop_type.slice(1)}`, 15, 12);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated by Smart Farming App`, 15, 19);

    // Date and Farm Info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 15, 35);
    doc.text(`Farm Size: ${guide.farm_layout.farm_size_hectares} hectares`, 120, 35);

    // 1. Spacing Configuration
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(22, 163, 74);
    doc.text('1. Optimal Spacing Configuration', 15, 45);

    const spacingData = [
        ['Row Spacing', `${guide.farm_layout.row_spacing_cm} cm`],
        ['Plant Spacing', `${guide.farm_layout.plant_spacing_cm} cm`],
        ['Plants per Hectare', guide.farm_layout.plants_per_hectare.toLocaleString()],
        ['Total Plants Needed', guide.farm_layout.total_plants.toLocaleString()],
        ['Field Dimensions', `${guide.farm_layout.field_dimension_m}m x ${guide.farm_layout.field_dimension_m}m`]
    ];

    autoTable(doc, {
        startY: 50,
        head: [['Parameter', 'Value']],
        body: spacingData,
        theme: 'grid',
        headStyles: { fillColor: [22, 163, 74], textColor: 255 },
        styles: { fontSize: 10, cellPadding: 3 },
        margin: { left: 15 }
    });

    // 2. Seed Requirements
    let yPos = (doc as any).lastAutoTable.finalY + 15;
    doc.setFontSize(14);
    doc.setTextColor(22, 163, 74);
    doc.text('2. Seed & Tools', 15, yPos);

    const seedData = [
        ['Seed Required', `${guide.seed_requirements.seed_required} ${guide.seed_requirements.unit}`],
        ['Note', guide.seed_requirements.includes_buffer]
    ];

    autoTable(doc, {
        startY: yPos + 5,
        body: seedData,
        theme: 'striped',
        styles: { fontSize: 10 },
        margin: { left: 15 },
        showHead: 'never'
    });

    yPos = (doc as any).lastAutoTable.finalY + 10;

    // Tools List
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text('Tools Required:', 15, yPos);
    yPos += 7;
    doc.setFontSize(10);
    guide.tools_needed.forEach((tool: string) => {
        doc.text(`• ${tool}`, 20, yPos);
        yPos += 5;
    });

    // 3. Instructions
    yPos += 10;
    doc.setFontSize(14);
    doc.setTextColor(22, 163, 74);
    doc.text('3. Step-by-Step Instructions', 15, yPos);
    yPos += 10;

    guide.planting_steps.forEach((step: any) => {
        // Check page break
        if (yPos > 270) {
            doc.addPage();
            yPos = 20;
        }

        // Step Title
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 0, 0);
        doc.text(`Step ${step.step}: ${step.title}`, 15, yPos);
        yPos += 6;

        // Step Instructions
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        step.instructions.forEach((inst: string) => {
            doc.text(`- ${inst}`, 20, yPos);
            yPos += 5;
        });
        yPos += 5;
    });

    // 4. Labor Estimate
    if (yPos > 260) {
        doc.addPage();
        yPos = 20;
    } else {
        yPos += 5;
    }

    doc.setFillColor(240, 253, 244); // light green bg
    doc.rect(15, yPos, 180, 25, 'F');
    doc.setDrawColor(22, 163, 74);
    doc.rect(15, yPos, 180, 25, 'S');

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(22, 163, 74);
    doc.text('Project Estimates:', 20, yPos + 8);

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(`Estimated Time: ${guide.estimated_time}`, 20, yPos + 18);
    doc.text(`Labor Required: ${guide.labor_required}`, 100, yPos + 18);

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - 20, 290);
        doc.text('Smart Farming Assistant - Row Spacing Innovation', 15, 290);
    }

    doc.save(`${guide.crop_type}_planting_guide.pdf`);
};
