-- Ensure farm profile fields edited by frontend persist in PostgreSQL
ALTER TABLE farms ADD COLUMN IF NOT EXISTS state TEXT;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS district TEXT;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS village TEXT;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS area_acres NUMERIC;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS crop_type TEXT;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS season TEXT;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS water_source TEXT;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS irrigation_type TEXT;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
