-- Sample courses for Indian farmers (English, Hindi, Marathi)
-- Insert into courses table for demo/testing

INSERT INTO courses (
  id, title, description, category, level, duration, lessons, thumbnail_emoji, language, instructor_name, rating, enrolled_count, price, currency, discount_percent, is_published
) VALUES
-- English Courses
(gen_random_uuid(), 'Introduction to Organic Farming', 'Learn the fundamentals of organic farming practices and sustainable agriculture. This comprehensive course covers soil health, natural pest control, and organic certification processes.', 'crop-management', 'beginner', '4 weeks', 12, '🌱', 'English', 'Dr. Rajesh Kumar', 4.8, 1250, 0, 'INR', 0, true),
(gen_random_uuid(), 'Modern Irrigation Techniques', 'Master efficient water management through drip irrigation, sprinkler systems, and smart farming technologies. Save water while increasing crop yields.', 'irrigation', 'intermediate', '3 weeks', 10, '💧', 'English', 'Prof. Anita Sharma', 4.6, 980, 0, 'INR', 0, true),
(gen_random_uuid(), 'Integrated Pest Management', 'Learn to control pests using eco-friendly methods. Covers biological control, pheromone traps, and minimal use of chemicals for sustainable farming.', 'pest-control', 'intermediate', '5 weeks', 15, '🐛', 'English', 'Dr. Suresh Patel', 4.7, 850, 0, 'INR', 0, true),
(gen_random_uuid(), 'Soil Health and Fertility Management', 'Understand soil testing, nutrient management, and organic amendments. Build healthy soil for sustainable farming and higher productivity.', 'soil-health', 'beginner', '3 weeks', 9, '🌾', 'English', 'Dr. Meera Singh', 4.9, 1100, 0, 'INR', 0, true),
(gen_random_uuid(), 'Farm Equipment Operation and Maintenance', 'Learn to operate and maintain essential farm machinery including tractors, harvesters, and implements. Safety procedures and troubleshooting included.', 'equipment', 'beginner', '4 weeks', 11, '🚜', 'English', 'Engineer Vikram Reddy', 4.5, 720, 0, 'INR', 0, true),

-- Hindi Courses
(gen_random_uuid(), 'जैविक खेती का परिचय', 'जैविक खेती और टिकाऊ कृषि की बुनियादी बातें सीखें। इस व्यापक पाठ्यक्रम में मिट्टी का स्वास्थ्य, प्राकृतिक कीट नियंत्रण और जैविक प्रमाणन प्रक्रियाएं शामिल हैं।', 'crop-management', 'beginner', '4 सप्ताह', 12, '🌱', 'Hindi', 'डॉ. राजेश कुमार', 4.8, 2100, 0, 'INR', 0, true),
(gen_random_uuid(), 'आधुनिक सिंचाई तकनीक', 'ड्रिप सिंचाई, स्प्रिंकलर सिस्टम और स्मार्ट खेती प्रौद्योगिकियों के माध्यम से कुशल जल प्रबंधन में महारत हासिल करें। फसल की पैदावार बढ़ाते हुए पानी बचाएं।', 'irrigation', 'intermediate', '3 सप्ताह', 10, '💧', 'Hindi', 'प्रो. अनीता शर्मा', 4.7, 1800, 0, 'INR', 0, true),
(gen_random_uuid(), 'समेकित कीट प्रबंधन', 'पर्यावरण के अनुकूल तरीकों से कीटों को नियंत्रित करना सीखें। टिकाऊ खेती के लिए जैविक नियंत्रण, फेरोमोन ट्रैप और रसायनों का न्यूनतम उपयोग शामिल है।', 'pest-control', 'intermediate', '5 सप्ताह', 15, '🐛', 'Hindi', 'डॉ. सुरेश पटेल', 4.6, 1650, 0, 'INR', 0, true),

-- Marathi Courses
(gen_random_uuid(), 'सेंद्रिय शेतीचा परिचय', 'सेंद्रिय शेती आणि शाश्वत कृषीचे मूलभूत तत्त्वे जाणून घ्या. या सर्वसमावेशक अभ्यासक्रमात मातीचे आरोग्य, नैसर्गिक कीड नियंत्रण आणि सेंद्रिय प्रमाणन प्रक्रिया समाविष्ट आहेत.', 'crop-management', 'beginner', '4 आठवडे', 12, '🌱', 'Marathi', 'डॉ. राजेश कुमार', 4.7, 890, 0, 'INR', 0, true),
(gen_random_uuid(), 'आधुनिक सिंचन तंत्र', 'ठिबक सिंचन, फवारा प्रणाली आणि स्मार्ट शेती तंत्रज्ञानाद्वारे कार्यक्षम जल व्यवस्थापनात प्रभुत्व मिळवा. पीक उत्पादन वाढवताना पाणी वाचवा.', 'irrigation', 'intermediate', '3 आठवडे', 10, '💧', 'Marathi', 'प्रा. अनीता शर्मा', 4.5, 760, 0, 'INR', 0, true);
