-- Sample videos for Indian farmers (English, Hindi, Marathi)
-- Insert into videos table for demo/testing

INSERT INTO videos (
  id, title, description, category, duration_seconds, video_type, video_url, video_id, thumbnail_emoji, creator_name, language, skill_level, view_count, like_count, is_published, is_featured
) VALUES
-- English Videos
(gen_random_uuid(), 'How to Start Organic Farming in India', 'Complete guide to starting your organic farm. Learn about soil preparation, seed selection, and natural fertilizers.', 'crop-management', 900, 'youtube', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'dQw4w9WgXcQ', '🌱', 'FarmTech India', 'English', 'beginner', 15420, 892, true, true),
(gen_random_uuid(), 'Drip Irrigation Installation Guide', 'Step-by-step installation of drip irrigation system. Includes parts list, setup process, and maintenance tips.', 'irrigation', 720, 'youtube', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'dQw4w9WgXcQ', '💧', 'Smart Farming TV', 'English', 'intermediate', 12350, 675, true, false),
(gen_random_uuid(), 'Natural Pest Control Methods', 'Learn to make organic pesticides at home using neem, garlic, and other natural ingredients.', 'pest-control', 600, 'youtube', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'dQw4w9WgXcQ', '🐞', 'Organic Farming Channel', 'English', 'beginner', 18900, 1120, true, true),
(gen_random_uuid(), 'Soil Testing at Home', 'Simple methods to test your soil pH and nutrient levels without expensive equipment.', 'soil-health', 480, 'youtube', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'dQw4w9WgXcQ', '🌾', 'Dr. Soil Science', 'English', 'beginner', 9850, 543, true, false),
(gen_random_uuid(), 'Tractor Maintenance Basics', 'Essential maintenance tasks every farmer should know. Keep your tractor running smoothly and avoid costly repairs.', 'equipment', 840, 'youtube', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'dQw4w9WgXcQ', '🚜', 'Farm Equipment Guide', 'English', 'intermediate', 11200, 689, true, false),

-- Hindi Videos
(gen_random_uuid(), 'भारत में जैविक खेती कैसे शुरू करें', 'अपनी जैविक खेती शुरू करने के लिए संपूर्ण मार्गदर्शिका। मिट्टी की तैयारी, बीज चयन और प्राकृतिक उर्वरकों के बारे में जानें।', 'crop-management', 900, 'youtube', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'dQw4w9WgXcQ', '🌱', 'फार्मटेक इंडिया', 'Hindi', 'beginner', 28500, 1650, true, true),
(gen_random_uuid(), 'ड्रिप सिंचाई स्थापना गाइड', 'ड्रिप सिंचाई प्रणाली की चरण-दर-चरण स्थापना। भागों की सूची, सेटअप प्रक्रिया और रखरखाव युक्तियां शामिल हैं।', 'irrigation', 720, 'youtube', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'dQw4w9WgXcQ', '💧', 'स्मार्ट फार्मिंग टीवी', 'Hindi', 'intermediate', 21400, 1280, true, false),
(gen_random_uuid(), 'प्राकृतिक कीट नियंत्रण विधियां', 'नीम, लहसुन और अन्य प्राकृतिक सामग्री का उपयोग करके घर पर जैविक कीटनाशक बनाना सीखें।', 'pest-control', 600, 'youtube', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'dQw4w9WgXcQ', '🐞', 'जैविक खेती चैनल', 'Hindi', 'beginner', 32100, 2050, true, true),
(gen_random_uuid(), 'घर पर मिट्टी परीक्षण', 'महंगे उपकरणों के बिना अपनी मिट्टी के पीएच और पोषक तत्वों के स्तर का परीक्षण करने के सरल तरीके।', 'soil-health', 480, 'youtube', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'dQw4w9WgXcQ', '🌾', 'डॉ. मृदा विज्ञान', 'Hindi', 'beginner', 16700, 920, true, false),

-- Marathi Videos
(gen_random_uuid(), 'भारतात सेंद्रिय शेती कशी सुरू करावी', 'तुमचे सेंद्रिय शेत सुरू करण्यासाठी संपूर्ण मार्गदर्शक. मातीची तयारी, बियाणे निवड आणि नैसर्गिक खतांबद्दल जाणून घ्या.', 'crop-management', 900, 'youtube', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'dQw4w9WgXcQ', '🌱', 'फार्मटेक इंडिया', 'Marathi', 'beginner', 12300, 710, true, false),
(gen_random_uuid(), 'ठिबक सिंचन स्थापना मार्गदर्शक', 'ठिबक सिंचन प्रणालीची चरण-दर-चरण स्थापना. भागांची यादी, सेटअप प्रक्रिया आणि देखभाल टिपा समाविष्ट आहेत.', 'irrigation', 720, 'youtube', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'dQw4w9WgXcQ', '💧', 'स्मार्ट फार्मिंग टीव्ही', 'Marathi', 'intermediate', 9800, 560, true, false),
(gen_random_uuid(), 'नैसर्गिक कीड नियंत्रण पद्धती', 'कडुलिंब, लसूण आणि इतर नैसर्गिक घटक वापरून घरी सेंद्रिय कीटकनाशके बनवायला शिका.', 'pest-control', 600, 'youtube', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'dQw4w9WgXcQ', '🐞', 'सेंद्रिय शेती चॅनेल', 'Marathi', 'beginner', 14500, 840, true, false);
